[workspace]
members = [
    "crates/invers-core",
    "crates/invers-cli",
    "crates/invers-gui",
    "crates/invers-web",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = []
license = "MIT OR Apache-2.0"
