[package]
name = "positize-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
positize-core = { path = "../positize-core" }

# TODO: Add cxx-qt dependencies in M2
# cxx-qt = "0.7"
# cxx-qt-lib = "0.7"
# cxx = "1.0"
# qml = "0.2"
